# Generated by Django 3.2.5 on 2021-11-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211120_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
